# Build Stage
FROM node:22-alpine AS build
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
# Declare the ARG for the env
ARG VITE_API_URL
# Make the env available during the build process
ENV VITE_API_URL=$VITE_API_URL
RUN npm run build

#Production Stage
FROM node:22-alpine
WORKDIR /app
RUN npm install -g serve
COPY --from=build /app/dist ./dist
EXPOSE 3000
CMD [ "serve", "-s", "dist"]